apiVersion: lsc.davenury.github.com/v1
kind: Scenario
metadata:
  name: sample
  namespace: operator-tryout
spec:
  phases:
    - duration: PT6S
      actions:
      - namespace: operator-tryout
        resourceType: deployment
        resourceName: subject
        action: scale
        value: 2
    - duration: PT3S
      actions:
        - namespace: operator-tryout
          resourceType: pod
          resourceName: nginx
          action: delete
    - duration: PT2S
      actions:
        - namespace: operator-tryout
          resourceType: service
          resourceName: my-service
          action: delete
