apiVersion: lsc.davenury.github.com/v1
kind: Scenario
metadata:
  name: new-scenario
  namespace: ddebowski
spec:
  phases:
    - duration: PT1M
      actions:
       - namespace: ddebowski
         resourceType: consensus leader
         action: delete
         deleteConsensusLeaderSpec:
           peersetId: 0
