apiVersion: lsc.davenury.github.com/v1
kind: Scenario
metadata:
  name: new-scenario2
  namespace: ddebowski
spec:
  phases:
    - duration: PT1M
      actions:
       - namespace: ddebowski
         resourceType: consensus follower
         action: delete count
         deleteConsensusFollowerCountSpec:
           peersetId: 0
           count: 1
