apiVersion: lsc.davenury.github.com/v1
kind: Scenario
metadata:
  name: sample
  namespace: operator-tryout
spec:
  phases:
    - durationInMillis: 60000
      actions:
      - namespace: operator-tryout
        resourceType: deployment
        resourceName: subject
        action: scale
        value: 2
      - namespace: operator-tryout
        resourceType: deployment
        resourceName: delete
        action: scale
    - durationInMillis: 30000
      actions:
        - namespace: operator-tryout
          resourceType: pod
          resourceName: ##
          action: delete
