apiVersion: lsc.davenury.github.com/v1
kind: Scenario
metadata:
  name: new-scenario
  namespace: ddebowski
spec:
  phases:
    - duration: PT30S
      actions:
       - namespace: ddebowski
         resourceType: deployment
         action: scale percentage
         scaleDeploymentPercentageSpec:
           value: 0
           percentage: 100
