apiVersion: lsc.davenury.github.com/v1
kind: Scenario
metadata:
  name: sample
  namespace: chaos-operator
spec:
  phases:
    - duration: PT6S
      actions:
      - namespace: chaos-operator
        resourceType: deployment
        resourceName: sample-deployment
        action: scale
        value: 2
    - duration: PT3S
      actions:
        - namespace: chaos-operator
          resourceType: pod
          resourceName: nginx
          action: delete
    - duration: PT2S
      actions:
        - namespace: chaos-operator
          resourceType: service
          resourceName: my-service
          action: delete
