apiVersion: lsc.davenury.github.com/v1
kind: Scenario
metadata:
  name: new-scenario
  namespace: default
spec:
  phases:
    - duration: PT30S
      actions:
       - namespace: default
         resourceType: deployment
         action: scale percentage
         scaleDeploymentPercentageSpec:
           value: 0
           percentage: 50
