apiVersion: lsc.davenury.github.com/v1
kind: Scenario
metadata:
  name: sample
  namespace: chaos-operator
spec:
  phases:
    - duration: PT30S
      actions:
        - namespace: chaos-operator
          resourceType: deployment
          resourceName: sample-deployment
          action: scale
          value: 2
        - namespace: chaos-operator
          resourceType: pod
          resourceName: nginx
          action: delete
    - duration: PT20S
      actions:
        - namespace: chaos-operator
          resourceType: service
          resourceName: my-service
          action: delete
