apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scenarioes.lsc.davenury.github.com
spec:
  group: lsc.davenury.github.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                actions:
                  type: array
                  items:
                    type: object
                    properties:
                      durationInMillis:
                        type: number
                      namespace:
                        type: string
                      resourceType:
                        type: string
                      resourceName:
                        type: string
                      action:
                        type: string
                      value:
                        type: number
                    required:
                      - durationInMillis
                      - namespace
                      - resourceType
                      - resourceName
                      - action
              required:
                - actions
            status:
              type: object
              properties:
                errorMessage:
                  type: string
  scope: Namespaced
  names:
    plural: scenarioes
    singular: scenario
    kind: Scenario