apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scenarioes.lsc.davenury.github.com
spec:
  group: lsc.davenury.github.com
  versions:
    - name: v1
      additionalPrinterColumns:
        - name: Status
          type: string
          jsonPath: .status.status
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                phases:
                  type: array
                  items:
                    type: object
                    properties:
                      duration:
                        type: string
                        description: ISO-8601 duration, e.g. PT5S
                      actions:
                        type: array
                        items:
                          type: object
                          properties:
                            namespace:
                              type: string
                            resourceType:
                              type: string
                            resourceName:
                              type: string
                            action:
                              type: string
                            deleteConsensusFollowerPercentageSpec:
                              type: object
                              properties:
                                  peersetId:
                                    type: number
                                  percentage:
                                    type: number
                              required:
                                - peersetId
                                - percentage
                            deleteConsensusFollowerCountSpec:
                              type: object
                              properties:
                                peersetId:
                                  type: number
                                count:
                                  type: number
                              required:
                                - peersetId
                                - count
                            deleteConsensusLeaderSpec:
                              type: object
                              properties:
                                peersetId:
                                  type: number
                              required:
                                - peersetId
                            scaleDeploymentSpec:
                              type: object
                              properties:
                                value:
                                  type: number
                              required:
                                - value
                            scaleDeploymentPercentageSpec:
                              type: object
                              properties:
                                value:
                                  type: number
                                labels:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      key:
                                        type: string
                                      value:
                                        type: string
                                percentage:
                                  type: number
                              required:
                                - value
                                - percentage
                            networkIsolationSpec:
                              type: object
                              properties:
                                labelKey:
                                  type: string
                                operator:
                                  type: string
                                values:
                                  type: array
                                  items:
                                    type: string
                              required:
                                - labelKey
                                - operator
                                - values
                          required:
                            - namespace
                            - resourceType
                            - action
                    required:
                      - actions
                      - duration
              required:
                - phases
            status:
              type: object
              properties:
                errorMessage:
                  type: string
                status:
                  type: string
  scope: Namespaced
  names:
    plural: scenarioes
    singular: scenario
    kind: Scenario