apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scenarioes.lsc.davenury.github.com
spec:
  group: lsc.davenury.github.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                phases:
                  type: array
                  items:
                    type: object
                    properties:
                      durationInMillis:
                        type: number
                      actions:
                        type: array
                        items:
                          type: object
                          properties:
                            namespace:
                              type: string
                            resourceType:
                              type: string
                            resourceName:
                              type: string
                            action:
                              type: string
                            value:
                              type: number
                          required:
                            - namespace
                            - resourceType
                            - resourceName
                            - action
                    required:
                      - actions
                      - durationInMillis
              required:
                - phases
            status:
              type: object
              properties:
                errorMessage:
                  type: string
  scope: Namespaced
  names:
    plural: scenarioes
    singular: scenario
    kind: Scenario