apiVersion: v1
kind: Pod
metadata:
  labels:
    app: visualizer
  name: visualizer
  namespace: chaos-operator
spec:
  containers:
  - name: visualizer
    image: ghcr.io/davenury/visualizer
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: chaos-operator
spec:
  selector:
    app: visualizer
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 80
  type: LoadBalancer