{{ if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default "chaos-operator" }}
  namespace: {{ .Values.namespace.name | default "default" }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-operator-admin
  namespace: {{ .Values.namespace.name | default "default" }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name | default "chaos-operator" }}
    namespace: {{ .Values.namespace.name | default "default" }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.serviceAccount.clusterRole.name | default "chaos-operator" }}
  apiGroup: ""

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.serviceAccount.clusterRole.name | default "chaos-operator" }}
  namespace: {{ .Values.namespace.name | default "default" }}
rules:
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - networkpolicies
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - deployments
      - services
      - configmaps
      - pods
      - scenarioes
    verbs:
      - '*'
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - services
      - configmaps
      - scenarioes
    verbs:
      - '*'
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - "lsc.davenury.github.com"
    resources:
      - scenarioes
      - scenarioes/status
    verbs:
      - '*'
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - '*'

{{ end }}