apiVersion: apps/v1
kind: Deployment
metadata:
{{ if .Values.operator }}
  name: {{ .Values.operator.deployment_name | default "chaos-operator" }}
  namespace: {{ .Values.namespace.name | default "default" }}
{{ else }}
  name: "chaos-operator"
  namespace: default
{{ end }}
spec:
  selector:
    matchLabels:
      app: chaos-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: chaos-operator
    spec:
      {{ if .Values.serviceAccount }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{ else }}
      serviceAccountName: chaos-operator
      {{ end }}
      containers:
        - name: operator
          {{ if .Values.operator }}
          image: {{ .Values.operator.image | default "ghcr.io/davenury/chaos-operator:latest" }}
          {{ else }}
          image: ghcr.io/davenury/chaos-operator:latest
          {{ end }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 1
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1