name: Gradle

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@v0.0.8
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
