name: K8s

on:
  pull_request:
    types:
      - closed
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: chaos-operator

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3

      - name: Log in container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version and push tag
        id: create_tag
        uses: anothrNick/github-tag-action@1.55.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DRY_RUN: true
          INITIAL_VERSION: 1.0.1
          DEFAULT_BUMP: patch

      - name: Bulid and push application image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: Dockerfile
          tags: ${{env.REGISTRY}}/davenury/chaos-operator:${{ steps.create_tag.outputs.new_tag }}

      - name: Bulid and push application image - latest
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: Dockerfile
          tags: ${{env.REGISTRY}}/davenury/chaos-operator:latest
